CREATE TABLE [dbo].[BlockGroup](
    [BlockGroupID] [int] NOT NULL,
	[GeoID] [varchar](255) NULL,
	[GeoID2] [float] NULL,
	[BlockGroup] [int] NULL,
	[Tract] [int] NULL,
	[County] [varchar](255) NULL,
	[BlockTract] [varchar](255) NULL,
	[TotalPop] [int] NULL,
	[TotalInc] [int] NULL,
	[IncLess10k] [int] NULL,
	[Inc10kTo14999] [int] NULL,
	[Inc15kTo19999] [int] NULL,
	[Inc20kTo24999] [int] NULL,
	[Inc25kTo29999] [int] NULL,
	[Inc30kTo34999] [int] NULL,
	[Inc35kTo39999] [int] NULL,
	[Inc40kTo44999] [int] NULL,
	[Inc45kTo49999] [int] NULL,
	[Inc50kTo59999] [int] NULL,
	[Inc60kTo74999] [int] NULL,
	[Inc75kTo99999] [int] NULL,
	[Inc100kTo124999] [int] NULL,
	[Inc125kTo149999] [int] NULL,
	[Inc150kTo199999] [int] NULL,
	[Inc200kTomore] [int] NULL,
	[TotalLabor] [int] NULL,
	[TotalInLaborForce] [int] NULL,
	[TotalNotInLaborForce] [int] NULL,
	[TotalCivilLabor] [int] NULL,
	[EmpCivilLabor] [int] NULL,
	[UnempCivilLabor] [int] NULL,
	[TotalArmedForces] [int] NULL,
	[TotalVacData] [int] NULL,
	[TotalOccHomes] [int] NULL,
	[TotalVacHomes] [int] NULL,
	[TotalORData] [int] NULL,
	[TotalOwner] [int] NULL,
	[TotalRenter] [int] NULL,
 CONSTRAINT [PK_BlockGroup] PRIMARY KEY CLUSTERED 
(
	[BlockGroupID] ASC
)
) ON [PRIMARY]
GO