ALTER TABLE dbo.Utility
DROP CONSTRAINT IF EXISTS FK_Utility_Address
GO

ALTER TABLE dbo.HousingProject
DROP CONSTRAINT IF EXISTS FK_Project_Address
GO

ALTER TABLE dbo.Address
DROP CONSTRAINT IF EXISTS FK_Address_Tax
GO

ALTER TABLE dbo.AddressJunctBG
DROP CONSTRAINT IF EXISTS FK_AddressJunctBG_Address
GO

ALTER TABLE dbo.AddressJunctBG
DROP CONSTRAINT IF EXISTS FK_AddressJunctBG_BG
GO

ALTER TABLE dbo.BGJunctTract
DROP CONSTRAINT IF EXISTS FK_BGJunctTract_BG
GO

ALTER TABLE dbo.BGJunctTract
DROP CONSTRAINT IF EXISTS FK_BGJunctTract_Tract
GO