DROP TABLE IF EXISTS dbo.Address
GO
DROP TABLE IF EXISTS dbo.AddressJunctBG
GO
DROP TABLE IF EXISTS dbo.BGJunctTract
GO
DROP TABLE IF EXISTS dbo.BlockGroup
GO
DROP TABLE IF EXISTS dbo.HousingProject
GO
DROP TABLE IF EXISTS dbo.RealEstate
GO
DROP TABLE IF EXISTS dbo.Tax
GO
DROP TABLE IF EXISTS dbo.Tract
GO
DROP TABLE IF EXISTS dbo.Utility
GO
DROP TABLE IF EXISTS dbo.Weather
GO