DROP TABLE IF EXISTS dbo.Tract
GO

CREATE TABLE [dbo].[Tract](
[TractID] [INT] NOT NULL,
[GEO.id] [VARCHAR](255) NOT NULL,
[GEO.id2] [VARCHAR](255) NOT NULL,
[Tract] [INT] NOT NULL,
[County] [VARCHAR](255) NOT NULL,
[Year] [INT] NOT NULL,
[HTotal] [INT] NOT NULL,
[FTotal] [INT] NOT NULL,
[MTotal] [INT] NOT NULL,
[NfTotal] [INT] NOT NULL,
[HIncomeLessThan10k] [FLOAT] NOT NULL,
[FIncomeLessThan10k] [FLOAT] NOT NULL,
[MIncomeLessThan10k] [FLOAT] NOT NULL,
[NfIncomeLessThan10k] [FLOAT] NOT NULL,
[HIncome10kTo14999] [FLOAT] NOT NULL,
[FIncome10kTo14999] [FLOAT] NOT NULL,
[MIncome10kTo14999] [FLOAT] NOT NULL,
[NfIncome10kTo14999] [FLOAT] NOT NULL,
[HIncome15kTo24999] [FLOAT] NOT NULL,
[FIncome15kTo24999] [FLOAT] NOT NULL,
[MIncome15kTo24999] [FLOAT] NOT NULL,
[NfIncome15kTo24999] [FLOAT] NOT NULL,
[HIncome25kTo34999] [FLOAT] NOT NULL,
[FIncome25kTo34999] [FLOAT] NOT NULL,
[MIncome25kTo34999] [FLOAT] NOT NULL,
[NfIncome25kTo34999] [FLOAT] NOT NULL,
[HIncome35kTo49999] [FLOAT] NOT NULL,
[FIncome35kTo49999] [FLOAT] NOT NULL,
[MIncome35kTo49999] [FLOAT] NOT NULL,
[NfIncome35kTo49999] [FLOAT] NOT NULL,
[HIncome50kTo74999] [FLOAT] NOT NULL,
[FIncome50kTo74999] [FLOAT] NOT NULL,
[MIncome50kTo74999] [FLOAT] NOT NULL,
[NfIncome50kTo74999] [FLOAT] NOT NULL,
[HIncome75kTo99999] [FLOAT] NOT NULL,
[FIncome75kTo99999] [FLOAT] NOT NULL,
[MIncome75kTo99999] [FLOAT] NOT NULL,
[NfIncome75kTo99999] [FLOAT] NOT NULL,
[HIncome100kTo149999] [FLOAT] NOT NULL,
[FIncome100kTo149999] [FLOAT] NOT NULL,
[MIncome100kTo149999] [FLOAT] NOT NULL,
[NfIncome100kTo149999] [FLOAT] NOT NULL,
[HIncome150kTo199999] [FLOAT] NOT NULL,
[FIncome150kTo199999] [FLOAT] NOT NULL,
[MIncome150kTo199999] [FLOAT] NOT NULL,
[NfIncome150kTo199999] [FLOAT] NOT NULL,
[HIncome200kOrMore] [FLOAT] NOT NULL,
[FIncome200kOrMore] [FLOAT] NOT NULL,
[MIncome200kOrMore] [FLOAT] NOT NULL,
[NfIncome200kOrMore] [FLOAT] NOT NULL,
[HIncomeMedian] [INT] NOT NULL,
[FIncomeMedian] [INT] NOT NULL,
[MIncomeMedian] [FLOAT] NULL,
[NfIncomeMedian] [FLOAT] NULL,
[HIncomeMean] [INT] NOT NULL,
[FIncomeMean] [INT] NOT NULL,
[MIncomeMean] [FLOAT] NULL,
[NfIncomeMean] [INT] NOT NULL,
[TotalPopulation] [INT] NOT NULL,
[MaleTotal] [INT] NOT NULL,
[FemaleTotal] [INT] NOT NULL,
[TotalAgeUnder5] [FLOAT] NOT NULL,
[MaleAgeUnder5] [FLOAT] NOT NULL,
[FemaleAgeUnder5] [FLOAT] NOT NULL,
[TotalAge5To9] [FLOAT] NOT NULL,
[MaleAge5To9] [FLOAT] NOT NULL,
[FemaleAge5To9] [FLOAT] NOT NULL,
[TotalAge10To14] [FLOAT] NOT NULL,
[MaleAge10To14] [FLOAT] NOT NULL,
[FemaleAge10To14] [FLOAT] NOT NULL,
[TotalAge15To19] [FLOAT] NOT NULL,
[MaleAge15To19] [FLOAT] NOT NULL,
[FemaleAge15To19] [FLOAT] NOT NULL,
[TotalAge20To24] [FLOAT] NOT NULL,
[MaleAge20To24] [FLOAT] NOT NULL,
[FemaleAge20To24] [FLOAT] NOT NULL,
[TotalAge25To29] [FLOAT] NOT NULL,
[MaleAge25To29] [FLOAT] NOT NULL,
[FemaleAge25To29] [FLOAT] NOT NULL,
[TotalAge30To34] [FLOAT] NOT NULL,
[MaleAge30To34] [FLOAT] NOT NULL,
[FemaleAge30To34] [FLOAT] NOT NULL,
[TotalAge35To39] [FLOAT] NOT NULL,
[MaleAge35To39] [FLOAT] NOT NULL,
[FemaleAge35To39] [FLOAT] NOT NULL,
[TotalAge40To44] [FLOAT] NOT NULL,
[MaleAge40To44] [FLOAT] NOT NULL,
[FemaleAge40To44] [FLOAT] NOT NULL,
[TotalAge45To49] [FLOAT] NOT NULL,
[MaleAge45To49] [FLOAT] NOT NULL,
[FemaleAge45To49] [FLOAT] NOT NULL,
[TotalAge50To54] [FLOAT] NOT NULL,
[MaleAge50To54] [FLOAT] NOT NULL,
[FemaleAge50To54] [FLOAT] NOT NULL,
[TotalAge55To59] [FLOAT] NOT NULL,
[MaleAge55To59] [FLOAT] NOT NULL,
[FemaleAge55To59] [FLOAT] NOT NULL,
[TotalAge60To64] [FLOAT] NOT NULL,
[MaleAge60To64] [FLOAT] NOT NULL,
[FemaleAge60To64] [FLOAT] NOT NULL,
[TotalAge65To69] [FLOAT] NOT NULL,
[MaleAge65To69] [FLOAT] NOT NULL,
[FemaleAge65To69] [FLOAT] NOT NULL,
[TotalAge70To74] [FLOAT] NOT NULL,
[MaleAge70To74] [FLOAT] NOT NULL,
[FemaleAge70To74] [FLOAT] NOT NULL,
[TotalAge75To79] [FLOAT] NOT NULL,
[MaleAge75To79] [FLOAT] NOT NULL,
[FemaleAge75To79] [FLOAT] NOT NULL,
[TotalAge80To84] [FLOAT] NOT NULL,
[MaleAge80To84] [FLOAT] NOT NULL,
[FemaleAge80To84] [FLOAT] NOT NULL,
[TotalAge85AndOver] [FLOAT] NOT NULL,
[MaleAge85AndOver] [FLOAT] NOT NULL,
[FemaleAge85AndOver] [FLOAT] NOT NULL,
[NonHispanic] [INT] NOT NULL,
[NonHispanicWhite] [INT] NOT NULL,
[NonHispanicBlack] [INT] NOT NULL,
[NonHispanicNative] [INT] NOT NULL,
[NonHispanicAsian] [INT] NOT NULL,
[NonHispanicPacificIslander] [INT] NOT NULL,
[NonHispanicOtherRace] [INT] NOT NULL,
[NonHispanic2Plus] [INT] NOT NULL,
[NonHispanic2PlusIncOther] [INT] NOT NULL,
[NonHispanic2PlusExcOther] [INT] NOT NULL,
[Hispanic] [INT] NOT NULL,
[HispanicWhite] [INT] NOT NULL,
[HispanicBlack] [INT] NOT NULL,
[HispanicNative] [INT] NOT NULL,
[HispanicAsian] [INT] NOT NULL,
[HispanicPacificIslander] [INT] NOT NULL,
[HispanicOtherRace] [INT] NOT NULL,
[Hispanic2Plus] [INT] NOT NULL,
[Hispanic2PlusIncOther] [INT] NOT NULL,
[Hispanic2PlusExcOther] [INT] NOT NULL,
[Total16AndOver] [INT] NOT NULL,
[LFPRate16AndOver] [FLOAT] NULL,
[EmpRatio16AndOver] [FLOAT] NULL,
[UnempRate16AndOver] [FLOAT] NOT NULL,
[TotalAge16To19] [INT] NOT NULL,
[LFPRateAge16To19] [FLOAT] NULL,
[EmpRatioAge16To19] [FLOAT] NULL,
[UnempRateAge16To19] [FLOAT] NULL,
[TotalAge20To24.1] [INT] NOT NULL,
[LFPRateAge20To24] [FLOAT] NULL,
[EmpRatioAge20To24] [FLOAT] NULL,
[UnempRateAge20To24] [FLOAT] NOT NULL,
[TotalAge25To29.1] [FLOAT] NULL,
[LFPRateAge25To29] [FLOAT] NULL,
[EmpRatioAge25To29] [FLOAT] NULL,
[UnempRateAge25To29] [FLOAT] NULL,
[TotalAge30To34.1] [FLOAT] NULL,
[LFPRateAge30To34] [FLOAT] NULL,
[EmpRatioAge30To34] [FLOAT] NULL,
[UnempRateAge30To34] [FLOAT] NULL,
[TotalAge35To44] [FLOAT] NULL,
[LFPRateAge35To44] [FLOAT] NULL,
[EmpRatioAge35To44] [FLOAT] NULL,
[UnempRateAge35To44] [FLOAT] NULL,
[TotalAge45To54] [INT] NOT NULL,
[LFPRateAge45To54] [FLOAT] NULL,
[EmpRatioAge45To54] [FLOAT] NULL,
[UnempRateAge45To54] [FLOAT] NOT NULL,
[TotalAge55To59.1] [FLOAT] NULL,
[LFPRateAge55To59] [FLOAT] NULL,
[EmpRatioAge55To59] [FLOAT] NULL,
[UnempRateAge55To59] [FLOAT] NULL,
[TotalAge60To64.1] [FLOAT] NULL,
[LFPRateAge60To64] [FLOAT] NULL,
[EmpRatioAge60To64] [FLOAT] NULL,
[UnempRateAge60To64] [FLOAT] NULL,
[TotalAge65To74] [INT] NOT NULL,
[LFPRateAge65To74] [FLOAT] NULL,
[EmpRatioAge65To74] [FLOAT] NULL,
[UnempRateAge65To74] [FLOAT] NULL,
[TotalAge75AndOver] [INT] NOT NULL,
[LFPRateAge75AndOver] [FLOAT] NULL,
[EmpRatioAge75AndOver] [FLOAT] NULL,
[UnempRateAge75AndOver] [FLOAT] NULL,
[TotalWhite] [FLOAT] NULL,
[LFPRateWhite] [FLOAT] NULL,
[EmpRatioWhite] [FLOAT] NULL,
[UnempRateWhite] [FLOAT] NULL,
[TotalBlack] [FLOAT] NULL,
[LFPRateBlack] [FLOAT] NULL,
[EmpRatioBlack] [FLOAT] NULL,
[UnempRateBlack] [FLOAT] NULL,
[TotalNative] [FLOAT] NULL,
[LFPRateNative] [FLOAT] NULL,
[EmpRatioNative] [FLOAT] NULL,
[UnempRateNative] [FLOAT] NULL,
[TotalAsian] [FLOAT] NULL,
[LFPRateAsian] [FLOAT] NULL,
[EmpRatioAsian] [FLOAT] NULL,
[UnempRateAsian] [FLOAT] NULL,
[TotalPacificIslander] [FLOAT] NULL,
[LFPRatePacificIslander] [FLOAT] NULL,
[EmpRatioPacificIslander] [FLOAT] NULL,
[UnempRatePacificIslander] [FLOAT] NULL,
[TotalOtherRace] [FLOAT] NULL,
[LFPRateOtherRace] [FLOAT] NULL,
[EmpRatioOtherRace] [FLOAT] NULL,
[UnempRateOtherRace] [FLOAT] NULL,
[Total2Plus] [INT] NOT NULL,
[LFPRate2Plus] [FLOAT] NULL,
[EmpRatio2Plus] [FLOAT] NULL,
[UnempRate2Plus] [FLOAT] NULL,
[TotalHispanic] [INT] NOT NULL,
[LFPRateHispanic] [FLOAT] NULL,
[EmpRatioHispanic] [FLOAT] NULL,
[UnempRateHispanic] [FLOAT] NULL,
[TotalWhiteNonHispanic] [INT] NOT NULL,
[LFPRateWhiteNonHispanic] [FLOAT] NULL,
[EmpRatioWhiteNonHispanic] [FLOAT] NULL,
[UnempRateWhiteNonHispanic] [FLOAT] NULL,
[Total20To64] [INT] NOT NULL,
[LFPRate20To64] [FLOAT] NULL,
[EmpRatio20To64] [FLOAT] NULL,
[UnempRate20To64] [FLOAT] NOT NULL,
[Total20To64Male] [FLOAT] NULL,
[LFPRate20To64Male] [FLOAT] NULL,
[EmpRatio20To64Male] [FLOAT] NULL,
[UnempRate20To64Male] [FLOAT] NULL,
[Total20To64Female] [FLOAT] NULL,
[LFPRate20To64Female] [FLOAT] NULL,
[EmpRatio20To64Female] [FLOAT] NULL,
[UnempRate20To64Female] [FLOAT] NULL,
[Total20To64FemaleChildrenUnder18] [FLOAT] NULL,
[LFPRate20To64FemaleChildrenUnder18] [FLOAT] NULL,
[EmpRatio20To64FemaleChildrenUnder18] [FLOAT] NULL,
[UnempRate20To64FemaleChildrenUnder18] [FLOAT] NULL,
[Total20To64FemaleChildrenUnder6] [FLOAT] NULL,
[LFPRate20To64FemaleChildrenUnder6] [FLOAT] NULL,
[EmpRatio20To64FemaleChildrenUnder6] [FLOAT] NULL,
[UnempRate20To64FemaleChildrenUnder6] [FLOAT] NULL,
[Total20To64FemaleChildrenUnder6And6To17] [FLOAT] NULL,
[LFPRate20To64FemaleChildrenUnder6And6To17] [FLOAT] NULL,
[EmpRatio20To64FemaleChildrenUnder6And6To17] [FLOAT] NULL,
[UnempRate20To64FemaleChildrenUnder6And6To17] [FLOAT] NULL,
[Total20To64FemaleChildren6To17] [FLOAT] NULL,
[LFPRate20To64FemaleChildren6To17] [FLOAT] NULL,
[EmpRatio20To64FemaleChildren6To17] [FLOAT] NULL,
[UnempRate20To64FemaleChildren6To17] [FLOAT] NULL,
[TotalBPL] [FLOAT] NULL,
[LFPRateBPL] [FLOAT] NULL,
[EmpRatioBPL] [FLOAT] NULL,
[UnempRateBPL] [FLOAT] NULL,
[TotalAPL] [FLOAT] NULL,
[LFPRateAPL] [FLOAT] NULL,
[EmpRatioAPL] [FLOAT] NULL,
[UnempRateAPL] [FLOAT] NULL,
[TotalDisabled] [FLOAT] NULL,
[LFPRateDisabled] [FLOAT] NULL,
[EmpRatioDisabled] [FLOAT] NULL,
[UnempRateDisabled] [FLOAT] NULL,
[TotalEdu25To64] [INT] NOT NULL,
[LFPRateEdu25To64] [FLOAT] NULL,
[EmpRatioEdu25To64] [FLOAT] NULL,
[UnempRateEdu25To64] [FLOAT] NOT NULL,
[TotalEdu25To64LessHS] [FLOAT] NULL,
[LFPRateEdu25To64LessHS] [FLOAT] NULL,
[EmpRatioEdu25To64LessHS] [FLOAT] NULL,
[UnempRateEdu25To64LessHS] [FLOAT] NULL,
[TotalEdu25To64HS] [FLOAT] NULL,
[LFPRateEdu25To64HS] [FLOAT] NULL,
[EmpRatioEdu25To64HS] [FLOAT] NULL,
[UnempRateEdu25To64HS] [FLOAT] NULL,
[TotalEdu25To64SomeCollege] [FLOAT] NULL,
[LFPRateEdu25To64SomeCollege] [FLOAT] NULL,
[EmpRatioEdu25To64SomeCollege] [FLOAT] NULL,
[UnempRateEdu25To64SomeCollege] [FLOAT] NULL,
[TotalEdu25To64Bachelors] [FLOAT] NULL,
[LFPRateEdu25To64Bachelors] [FLOAT] NULL,
[EmpRatioEdu25To64Bachelors] [FLOAT] NULL,
[UnempRateEdu25To64Bachelors] [FLOAT] NULL,

    CONSTRAINT [PK_TractID] PRIMARY KEY CLUSTERED
    (
        [TractID] asc
    )
) ON [PRIMARY]
GO

BULK INSERT Tract
FROM 'Tract_v03.csv'
WITH (DATA_SOURCE = 'databasestore',
    FIRSTROW=2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0a',
    FORMAT = 'CSV')
GO